name: Second Workflow
on: workflow_dispatch
jobs: 
  second-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: |
          echo "Hello world!"
          touch abc.txt
          echo "test" >> abc.txt
          cat abc.txt
